import textures as tx

# name: (display name, top, side, bottom, plan colour, flags)
B = {}
def reg(key, name, top, side=None, bottom=None, color='#888888', translucent=False, stairs=None, slab=None,
        fence=None, wall=None, front=None, cutout=False, glow=False, **extra):
    """Register a block. Extra keyword args (Volume 2) are kept on the entry, for example
    light=10 (light level it gives off), item='Copper Lantern' (name in the block list),
    pane='Copper Bars' (item name when used with the pane shape), new='26.50' (game version that added it)."""
    B[key] = dict(key=key, name=name, top=top, side=side if side is not None else top,
                  bottom=bottom if bottom is not None else top, color=color, translucent=translucent,
                  stairs=stairs, slab=slab, fence=fence, wall=wall, front=front, cutout=cutout, glow=glow, **extra)

def woods():
    for k, n, c, lc, inner in [('oak', 'Oak', '#b8945f', '#6b5031', '#b8945f'), ('spruce', 'Spruce', '#7a5a36', '#3b2a18', '#7a5a36'),
                               ('birch', 'Birch', '#d7c68b', '#e8e4d8', '#d7c68b'), ('dark_oak', 'Dark Oak', '#4a3219', '#3a2a18', '#4a3219'),
                               ('jungle', 'Jungle', '#a8744a', '#5a4520', '#a8744a'), ('cherry', 'Cherry', '#e3b3aa', '#3a2430', '#e3b3aa')]:
        reg(f'{k}_planks', f'{n} Planks', tx.planks(c, k), color=c, stairs=f'{n} Stairs', slab=f'{n} Slab', fence=f'{n} Fence')
        side = tx.log_side(lc, k + 'log')
        if k == 'birch':
            side = tx.noise('#e8e4d8', 6, 'birch'); side[[2, 7, 12], 3:9, :3] = tx.hexrgb('#2b2b2b'); side[[5, 13], 9:14, :3] = tx.hexrgb('#2b2b2b')
        reg(f'{k}_log', f'{n} Log', tx.log_top(lc, inner, k), side, color=lc)
        reg(f'{k}_door', f'{n} Door', tx.door(c, True, k + 'd'), tx.door(c, False, k + 'd2'), color=c)
        reg(f'{k}_trapdoor', f'{n} Trapdoor', tx.trapdoor(c, k + 't'), color=c)
woods()
reg('oak_leaves', 'Oak Leaves', tx.leaves('#4f8a2e'), color='#4f8a2e')
reg('spruce_leaves', 'Spruce Leaves', tx.leaves('#3a5f3a', 'spl'), color='#3a5f3a')
reg('birch_leaves', 'Birch Leaves', tx.leaves('#79a84e', 'bil'), color='#79a84e')
reg('cherry_leaves', 'Cherry Leaves', tx.leaves('#f0a6c8', 'chl'), color='#f0a6c8')
reg('azalea_leaves', 'Flowering Azalea Leaves', tx.leaves('#5d8a36', 'azl'), color='#5d8a36')

reg('stone', 'Stone', tx.stone('#8f8f8f'), color='#8f8f8f', stairs='Stone Stairs', slab='Stone Slab', )
reg('cobblestone', 'Cobblestone', tx.cobble('#8a8a8a'), color='#7a7a7a', stairs='Cobblestone Stairs', slab='Cobblestone Slab', wall='Cobblestone Wall')
reg('mossy_cobblestone', 'Mossy Cobblestone', tx.cobble('#8a8a8a', 'mc', '#5f7f3a'), color='#6f7f5a', stairs='Mossy Cobblestone Stairs', slab='Mossy Cobblestone Slab', wall='Mossy Cobblestone Wall')
reg('stone_bricks', 'Stone Bricks', tx.bricks('#8c8c8c', '#5f5f5f', 8, 16, 'sb', 7), color='#8c8c8c', stairs='Stone Brick Stairs', slab='Stone Brick Slab', wall='Stone Brick Wall')
reg('mossy_stone_bricks', 'Mossy Stone Bricks', tx.mossy_stone_bricks(), color='#7a8a6a', stairs='Mossy Stone Brick Stairs', slab='Mossy Stone Brick Slab', wall='Mossy Stone Brick Wall')
reg('bricks', 'Bricks', tx.bricks('#9b4f3c', '#c9b8a8', 4, 8, 'br', 10), color='#9b4f3c', stairs='Brick Stairs', slab='Brick Slab', wall='Brick Wall')
reg('deepslate_bricks', 'Deepslate Bricks', tx.bricks('#4a4a50', '#2e2e33', 4, 8, 'dsb', 6), color='#4a4a50', stairs='Deepslate Brick Stairs', slab='Deepslate Brick Slab', wall='Deepslate Brick Wall')
reg('polished_deepslate', 'Polished Deepslate', tx.panel('#4d4d52', '#3a3a3f', 'pd'), color='#4d4d52', stairs='Polished Deepslate Stairs', slab='Polished Deepslate Slab', wall='Polished Deepslate Wall')
reg('smooth_stone', 'Smooth Stone', tx.smooth_stone(), color='#a4a4a4', slab='Smooth Stone Slab')
reg('polished_andesite', 'Polished Andesite', tx.panel('#8a8f8f', '#7a7f7f', 'pa', 6), color='#8a8f8f', stairs='Polished Andesite Stairs', slab='Polished Andesite Slab')
reg('andesite', 'Andesite', tx.stone('#888c8c', 'and', 14), color='#888c8c', stairs='Andesite Stairs', slab='Andesite Slab', wall='Andesite Wall')
reg('quartz_block', 'Block of Quartz', tx.quartz(), color='#ece6dc', stairs='Quartz Stairs', slab='Quartz Slab')
reg('quartz_pillar', 'Quartz Pillar', tx.quartz(), tx.quartz_pillar(), color='#e3dccf')
reg('sandstone', 'Sandstone', tx.noise('#e0cf95', 5, 'sst'), tx.sandstone_side(), color='#e0cf95', stairs='Sandstone Stairs', slab='Sandstone Slab', wall='Sandstone Wall')
reg('sand', 'Sand', tx.sand(), color='#e3d49f')
reg('gravel', 'Gravel', tx.gravel(), color='#8c8480')
reg('grass_block', 'Grass Block', tx.grass_top(), tx.grass_side(), tx.dirt(), color='#6aa84f')
reg('dirt', 'Dirt', tx.dirt(), color='#8a5f3c')
reg('dirt_path', 'Dirt Path', tx.path_top(), tx.dirt(), color='#b08a52')
reg('coarse_dirt', 'Coarse Dirt', tx.noise('#77533a', 16, 'cd'), color='#77533a')
reg('podzol', 'Podzol', tx.noise('#6a4a26', 14, 'pdz'), tx.dirt(), color='#6a4a26')
reg('moss_block', 'Moss Block', tx.moss(), color='#5b7f2c')
reg('snow_block', 'Snow Block', tx.snow(), color='#f4f8fa')
reg('water', 'Water', tx.water(), color='#3f76e4', translucent=True)
reg('glass', 'Glass', tx.glass(), color='#bfe3ee', translucent=True)
for k, n, c in [('light_blue', 'Light Blue', '#9fd3ea'), ('white', 'White', '#f2f2f2'), ('black', 'Black', '#3a3a3a'), ('purple', 'Purple', '#9c6ad0'), ('red', 'Red', '#d05050'), ('orange', 'Orange', '#f0a040'), ('yellow', 'Yellow', '#f0da50'), ('lime', 'Lime', '#8ad04a'), ('cyan', 'Cyan', '#50b8c8'), ('blue', 'Blue', '#5070d0'), ('magenta', 'Magenta', '#d070c8'), ('pink', 'Pink', '#f0a8c8'), ('green', 'Green', '#5a8a3a')]:
    reg(f'{k}_stained_glass', f'{n} Stained Glass', tx.glass(c, 120, c), color=c, translucent=True)
for k, n, c in [('white', 'White', '#e9ecec'), ('orange', 'Orange', '#f07613'), ('magenta', 'Magenta', '#bd44b3'), ('light_blue', 'Light Blue', '#3aafd9'),
                ('yellow', 'Yellow', '#f8c627'), ('lime', 'Lime', '#70b919'), ('pink', 'Pink', '#ed8dac'), ('gray', 'Gray', '#3e4447'),
                ('light_gray', 'Light Gray', '#8e8e86'), ('cyan', 'Cyan', '#158991'), ('purple', 'Purple', '#792aac'), ('blue', 'Blue', '#35399d'),
                ('brown', 'Brown', '#724728'), ('green', 'Green', '#546d1b'), ('red', 'Red', '#a12722'), ('black', 'Black', '#141519')]:
    reg(f'{k}_wool', f'{n} Wool', tx.wool(c, k), color=c)
    reg(f'{k}_carpet', f'{n} Carpet', tx.wool(c, k), color=c)
    reg(f'{k}_concrete', f'{n} Concrete', tx.concrete(c, k), color=c)
    reg(f'{k}_bed', f'{n} Bed', tx.wool(c, k + 'bed'), tx.planks('#a8743e', 'bedside'), color=c)
reg('terracotta', 'Terracotta', tx.terracotta('#9a5d42'), color='#9a5d42')
reg('white_terracotta', 'White Terracotta', tx.terracotta('#d1b1a1'), color='#d1b1a1')
reg('iron_block', 'Block of Iron', tx.iron_tex(), color='#dcdcdc')
reg('gold_block', 'Block of Gold', tx.gold_tex(), color='#f2c230')
reg('diamond_block', 'Block of Diamond', tx.diamond_tex(), color='#6fe0d6')
reg('emerald_block', 'Block of Emerald', tx.emerald_tex(), color='#41c46b')
reg('lapis_block', 'Block of Lapis Lazuli', tx.lapis_tex(), color='#2f56b0')
reg('copper_block', 'Block of Copper', tx.copper_tex(), color='#c26b43')
reg('redstone_block', 'Block of Redstone', tx.panel('#b0180e', '#7a0f08', 'rsb', 8), color='#b0180e')
reg('coal_block', 'Block of Coal', tx.noise('#1f1f1f', 6, 'coal'), color='#1f1f1f')
reg('obsidian', 'Obsidian', tx.obsidian(), color='#1a1325')
reg('crying_obsidian', 'Crying Obsidian', tx.obsidian(), color='#2a1340')
reg('glowstone', 'Glowstone', tx.glowstone(), color='#e3b75a', glow=True)
reg('sea_lantern', 'Sea Lantern', tx.sea_lantern(), color='#cfe8e0', glow=True)
reg('shroomlight', 'Shroomlight', tx.noise('#f09a3a', 14, 'shr'), color='#f09a3a', glow=True)
reg('amethyst_block', 'Block of Amethyst', tx.amethyst(), color='#8c5fc7')
reg('purpur_block', 'Purpur Block', tx.panel('#a97ea9', '#8a5f8a', 'pur', 6), color='#a97ea9', stairs='Purpur Stairs', slab='Purpur Slab')
reg('bookshelf', 'Bookshelf', tx.planks('#a07a45', 'bkt'), tx.bookshelf_side(), color='#8a6a3a')
reg('hay_block', 'Hay Bale', tx.noise('#c9a227', 10, 'hayt'), tx.hay_side(), color='#c9a227')
reg('crafting_table', 'Crafting Table', tx.planks('#8a5f33', 'ctt'), tx.crafting_side(), color='#8a5f33')
reg('furnace', 'Furnace', tx.smooth_stone(), tx.stone('#7d7d7d', 'furs'), front=tx.furnace_front(), color='#7d7d7d')
reg('lit_furnace', 'Furnace', tx.smooth_stone(), tx.stone('#7d7d7d', 'furs'), front=tx.furnace_front(True), color='#7d7d7d')
reg('barrel', 'Barrel', tx.barrel_top(), tx.barrel_side(), color='#8a5f33')
reg('chest', 'Chest', tx.chest_side(), tx.chest_side(), color='#b07a2e')
reg('pumpkin', 'Pumpkin', tx.noise('#c9791a', 8, 'pkt'), tx.pumpkin_side(), color='#d9861c')
reg('melon', 'Melon', tx.melon_side(), color='#6f9a2c')
reg('redstone_lamp', 'Redstone Lamp', tx.lamp(False), color='#6e3b1f')
reg('lit_redstone_lamp', 'Redstone Lamp', tx.lamp(True), color='#f6c85f', glow=True)
reg('note_block', 'Note Block', tx.note_block(), color='#6d4527')
reg('sticky_piston', 'Sticky Piston', tx.piston_face(True), tx.piston_side(), tx.stone('#8a8a8a', 'pb'), color='#79c05a')
reg('piston', 'Piston', tx.piston_face(False), tx.piston_side(), tx.stone('#8a8a8a', 'pb'), color='#a8743e')
reg('daylight_detector', 'Daylight Detector', tx.daylight_top(), tx.planks('#c9b48a', 'dls'), color='#9fc3d6')
reg('hopper', 'Hopper', tx.hopper_tex(), color='#4a4a4a')
reg('tnt', 'TNT', tx.noise('#d63c2f', 8, 'tntt'), tx.tnt_side(), color='#d63c2f')
reg('redstone_dust', 'Redstone Dust', tx.redstone_tex(), color='#e02020')
reg('redstone_torch', 'Redstone Torch', tx.redstone_tex(), color='#e02020')
reg('torch', 'Torch', tx.solid('#ffd24a'), tx.solid('#7a5a36'), color='#ffd24a', glow=True)
reg('lantern', 'Lantern', tx.lantern_tex(), color='#ffcf5a', glow=True)
reg('soul_lantern', 'Soul Lantern', tx.solid('#63d8e0'), color='#63d8e0', glow=True)
reg('chain', 'Chain', tx.solid('#3e4247'), color='#3e4247')
reg('iron_bars', 'Iron Bars', tx.iron_bars(), color='#6f6f6f', cutout=True)
reg('ladder', 'Ladder', tx.ladder(), color='#9c7440', cutout=True)
reg('iron_door', 'Iron Door', tx.panel('#d0d0d0', '#9a9a9a', 'idoor'), color='#c8c8c8')
reg('stone_pressure_plate', 'Stone Pressure Plate', tx.smooth_stone(), color='#a4a4a4')
reg('oak_pressure_plate', 'Oak Pressure Plate', tx.planks('#b8945f', 'opp'), color='#b8945f')
reg('stone_button', 'Stone Button', tx.smooth_stone(), color='#a4a4a4')
reg('oak_button', 'Oak Button', tx.planks('#b8945f', 'obt'), color='#b8945f')
reg('lever', 'Lever', tx.stone('#7d7d7d', 'lev'), tx.solid('#7a5a36'), color='#7a5a36')
reg('oak_sign', 'Oak Sign', tx.planks('#b8945f', 'sign'), color='#b8945f')
reg('spruce_sign', 'Spruce Sign', tx.planks('#7a5a36', 'ssign'), color='#7a5a36')
reg('poppy', 'Poppy', tx.solid('#d42a2a'), tx.solid('#3f7a2a'), color='#d42a2a')
reg('dandelion', 'Dandelion', tx.solid('#f5d932'), tx.solid('#3f7a2a'), color='#f5d932')
reg('cornflower', 'Cornflower', tx.solid('#4f6ee0'), tx.solid('#3f7a2a'), color='#4f6ee0')
reg('allium', 'Allium', tx.solid('#b56ae0'), tx.solid('#3f7a2a'), color='#b56ae0')
reg('oxeye_daisy', 'Oxeye Daisy', tx.solid('#f4f4f4'), tx.solid('#3f7a2a'), color='#f4f4f4')
reg('short_grass', 'Short Grass', tx.solid('#5f9a3a'), color='#5f9a3a')
reg('sweet_berry_bush', 'Sweet Berry Bush', tx.leaves('#3f6a2a', 'sbb'), color='#3f6a2a')
reg('flower_pot', 'Flower Pot', tx.solid('#8a4a2a'), color='#8a4a2a')
reg('bell', 'Bell', tx.bell_tex(), color='#f2c230')
reg('campfire', 'Campfire', tx.solid('#ff9a2a'), tx.log_side('#5a4520', 'camp'), color='#ff9a2a', glow=True)
reg('cauldron', 'Cauldron', tx.noise('#3a3a3a', 5, 'cau'), color='#3a3a3a')
reg('anvil', 'Anvil', tx.noise('#444444', 5, 'anv'), color='#444444')
reg('scaffolding', 'Scaffolding', tx.planks('#d9b56a', 'scf'), color='#d9b56a')
reg('white_banner', 'White Banner', tx.wool('#e9ecec', 'ban'), color='#e9ecec')
reg('red_banner', 'Red Banner', tx.wool('#a12722', 'rban'), color='#a12722')
reg('blue_banner', 'Blue Banner', tx.wool('#35399d', 'bban'), color='#35399d')
reg('wheat', 'Wheat Crops', tx.solid('#c8b44a'), color='#c8b44a')
reg('farmland', 'Farmland', tx.noise('#5a3a1f', 10, 'farm'), tx.dirt(), color='#5a3a1f')
reg('oak_fence_gate', 'Oak Fence Gate', tx.planks('#b8945f', 'gate'), color='#b8945f')
reg('spruce_fence_gate', 'Spruce Fence Gate', tx.planks('#7a5a36', 'sgate'), color='#7a5a36')
reg('end_rod', 'End Rod', tx.solid('#f4f0e6'), color='#f4f0e6', glow=True)
reg('lightning_rod', 'Lightning Rod', tx.solid('#c26b43'), color='#c26b43')
reg('enchanting_table', 'Enchanting Table', tx.noise('#2a1a3a', 6, 'ench'), tx.obsidian(), color='#2a1a3a')
reg('bone_block', 'Bone Block', tx.noise('#e5dfc5', 5, 'bone'), color='#e5dfc5')

# ---- blocks added for the Showcase and Top 10 scenes
reg('netherrack', 'Netherrack', tx.noise('#7a2e2e', 18, 'nrack'), color='#7a2e2e')
reg('nether_bricks', 'Nether Bricks', tx.bricks('#3b1c22', '#23100f', 4, 8, 'nb', 6), color='#3b1c22', stairs='Nether Brick Stairs', slab='Nether Brick Slab', fence='Nether Brick Fence')
reg('soul_sand', 'Soul Sand', tx.noise('#54402f', 14, 'soul'), color='#54402f')
reg('basalt', 'Basalt', tx.noise('#4d4d52', 10, 'bas'), tx.log_side('#4a4a50', 'bass'), color='#4d4d52')
reg('blackstone', 'Blackstone', tx.stone('#2e2a30', 'blk', 10), color='#2e2a30')
reg('magma_block', 'Magma Block', tx.glowstone() * 0 + tx.noise('#8a3a12', 22, 'mag'), color='#8a3a12', glow=True)
reg('lava', 'Lava', tx.noise('#e8671c', 24, 'lava'), color='#e8671c', glow=True)
reg('end_stone', 'End Stone', tx.noise('#dcdca0', 10, 'ends'), color='#dcdca0')
reg('end_stone_bricks', 'End Stone Bricks', tx.bricks('#dcdca0', '#b8b880', 4, 8, 'esb', 5), color='#dcdca0')
reg('deepslate', 'Deepslate', tx.stone('#505056', 'dsl', 9), color='#505056')
def _ore(base, spot, seed):
    img = tx.stone(base, seed, 9); r = tx._rng(seed + 'o')
    for (x, y) in [(2, 2), (9, 3), (4, 9), (11, 10), (7, 6)]:
        img[y:y + 3, x:x + 3, :3] = tx.hexrgb(spot); img[y, x, :3] = 255
    return img
reg('diamond_ore', 'Deepslate Diamond Ore', _ore('#505056', '#6fe8dc', 'dore'), color='#6fe8dc')
reg('gold_ore', 'Deepslate Gold Ore', _ore('#505056', '#f2c230', 'gore'), color='#f2c230')
reg('sculk', 'Sculk', tx.noise('#0d2a33', 12, 'sculk'), color='#0d2a33', glow=False)
reg('reinforced_deepslate', 'Reinforced Deepslate', tx.panel('#3a3d3f', '#6a6d62', 'rds', 6), color='#3a3d3f')
reg('tuff_bricks', 'Tuff Bricks', tx.bricks('#6c6d66', '#4f504a', 8, 8, 'tuffb', 6), color='#6c6d66', stairs='Tuff Brick Stairs', slab='Tuff Brick Slab')
reg('oxidized_copper', 'Oxidized Copper', tx.panel('#4fa38c', '#3b7f6c', 'oxc', 8), color='#4fa38c')
reg('weathered_copper', 'Weathered Copper', tx.panel('#6c9a74', '#557a5b', 'wec', 8), color='#6c9a74')
reg('pale_oak_log', 'Pale Oak Log', tx.log_top('#5a5450', '#cfc6be', 'pale'), tx.log_side('#5a5450', 'palelog'), color='#5a5450')
reg('pale_oak_leaves', 'Pale Oak Leaves', tx.leaves('#8a9488', 'pal'), color='#8a9488')
reg('pale_moss', 'Pale Moss Block', tx.noise('#8f9a8c', 10, 'pmoss'), color='#8f9a8c')
reg('mycelium', 'Mycelium', tx.noise('#77687a', 12, 'myc'), tx.dirt(), tx.dirt(), color='#77687a')
reg('red_mushroom_block', 'Red Mushroom Block', tx.noise('#b52c2c', 8, 'rmb'), color='#b52c2c')
reg('mushroom_stem', 'Mushroom Stem', tx.noise('#dcd6c8', 5, 'mst'), color='#dcd6c8')
reg('sulfur_block', 'Sulfur Block', tx.noise('#d9c63a', 16, 'sulf'), color='#d9c63a')
reg('prismarine', 'Prismarine', tx.noise('#5fa89a', 14, 'pris'), color='#5fa89a')
reg('dark_prismarine', 'Dark Prismarine', tx.panel('#2f5e52', '#244a41', 'dpris', 6), color='#2f5e52')
reg('cyan_terracotta', 'Cyan Terracotta', tx.terracotta('#56595b'), color='#56595b')
reg('carved_pumpkin', 'Carved Pumpkin', tx.noise('#c9791a', 8, 'cpt'), tx.pumpkin_side(), front=None, color='#d9861c')
reg('dried_kelp_block', 'Dried Kelp Block', tx.noise('#3b4a2a', 10, 'kelp'), color='#3b4a2a')
reg('cloud', 'White Wool', tx.wool('#fbfbfb', 'cloud'), color='#fbfbfb')
reg('yellow_terracotta', 'Yellow Terracotta', tx.terracotta('#b8842f'), color='#b8842f')
reg('light_blue_wool2', 'Light Blue Wool', tx.wool('#8fcbe8', 'lbw'), color='#8fcbe8')

def _carved_face():
    img = tx.pumpkin_side().copy()
    img[4:7, 3:6, :3] = tx.hexrgb('#2a1606'); img[4:7, 10:13, :3] = tx.hexrgb('#2a1606'); img[10:12, 4:12, :3] = tx.hexrgb('#2a1606')
    return img
B['carved_pumpkin']['front'] = _carved_face()
